version: "4"
services:
  controller1:
    image: apache/kafka:latest
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,OUTSIDE:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller1:9093,2@controller2:9093,3@controller3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIR: /var/lib/kafka/data
    networks:
      - kafka-net
    volumes:
      - controller1-data:/var/lib/kafka/data

  controller2:
    image: apache/kafka:latest
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,OUTSIDE:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller1:9093,2@controller2:9093,3@controller3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIR: /var/lib/kafka/data
    networks:
      - kafka-net
    volumes:
      - controller2-data:/var/lib/kafka/data

  controller3:
    image: apache/kafka:latest
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,OUTSIDE:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller1:9093,2@controller2:9093,3@controller3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIR: /var/lib/kafka/data
    networks:
      - kafka-net
    volumes:
      - controller3-data:/var/lib/kafka/data

  broker1:
    image: apache/kafka:latest
    ports:
      - 19092:19092
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.kafka == true ]
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'OUTSIDE://0.0.0.0:19092,INTERNAL://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'OUTSIDE://${PUBLIC_FQDN}:19092,INTERNAL://broker1:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,OUTSIDE:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller1:9093,2@controller2:9093,3@controller3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIR: /var/lib/kafka/data
    depends_on:
      - controller1
      - controller2
      - controller3
    networks:
      - kafka-net
    volumes:
      - broker-1-data:/var/lib/kafka/data

  broker2:
    image: apache/kafka:latest
    ports:
      - 29092:19092
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.kafka == true ]
    environment:
      KAFKA_NODE_ID: 5
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'OUTSIDE://0.0.0.0:19092,INTERNAL://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'OUTSIDE://${PUBLIC_FQDN}:29092,INTERNAL://broker2:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,OUTSIDE:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller1:9093,2@controller2:9093,3@controller3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIR: /var/lib/kafka/data
    depends_on:
      - controller1
      - controller2
      - controller3
    networks:
      - kafka-net
    volumes:
      - broker-2-data:/var/lib/kafka/data

  broker3:
    image: apache/kafka:latest
    ports:
      - 39092:19092
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.kafka == true ]
    environment:
      KAFKA_NODE_ID: 6
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'OUTSIDE://0.0.0.0:19092,INTERNAL://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'OUTSIDE://${PUBLIC_FQDN}:39092,INTERNAL://broker3:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,OUTSIDE:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller1:9093,2@controller2:9093,3@controller3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIR: /var/lib/kafka/data
    depends_on:
      - controller1
      - controller2
      - controller3
    networks:
      - kafka-net
    volumes:
      - broker-3-data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8280:8080
    depends_on:
      - kafka
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - kafka-net
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      TRUST_STORE: "/opt/cert/ui-for-apache-kafka.p12"
      TRUST_STORE_PASSWORD: "Fvck2022!"

      # OAUTH2
      # AUTH_TYPE: OAUTH2
      # AUTH_OAUTH2_CLIENT_GITHUB_PROVIDER: github
      # AUTH_OAUTH2_CLIENT_GITHUB_CLIENTID:  ${GITHUB_CLIENTID}
      # AUTH_OAUTH2_CLIENT_GITHUB_CLIENTSECRET: ${GITHUB_CLIENTSECRET}
      # AUTH_OAUTH2_CLIENT_GITHUB_SCOPE: read:org
      # AUTH_OAUTH2_CLIENT_GITHUB_USER_NAME_ATTRIBUTE: login
      # AUTH_OAUTH2_CLIENT_GITHUB_CUSTOM_PARAMS_TYPE: github
      # AUTH_OAUTH2_CLIENT_GITHUB_REDIRECT_URI: https://kafka.publicnode.eu/login/oauth2/code/github

      # BASIC AUTH
      AUTH_TYPE: "LOGIN_FORM"
      SPRING_SECURITY_USER_NAME: ${KAFKA_UI_USERNAME}
      SPRING_SECURITY_USER_PASSWORD: ${KAFKA_UI_PASSWORD}
      SPRINT_BOOT_ADMIN_CLIENT_USERNAME: ${KAFKA_UI_USERNAME}
      SPRINT_BOOT_ADMIN_CLIENT_PASSWORD: ${KAFKA_UI_PASSWORD}
    # configs:
    #   - source: kafka_ui_roles
    #     target: /roles.yml
    #   - source: kafka_ui_sprint_config
    #     target: /sprint-config.yml
    # secrets:
    #   - kafka_ui_client_id
    #   - kafka_ui_client_secret
    volumes:
      - kafka-ui-data:/etc/kafkaui/

  postgresql:
    image: postgres:14
    hostname: postgresql
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - kafka-net
    environment:
      POSTGRES_DB: "conduktor-console"
      POSTGRES_USER: "conduktor"
      POSTGRES_PASSWORD: "ouch-pupa-overscores-prevalent"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"

  conduktor-console:
    image: conduktor/conduktor-console:1.27.0
    depends_on:
      - postgresql
    ports:
      - "8480:8080"
    volumes:
      - conduktor_data:/var/conduktor
    networks:
      - kafka-net
    environment:
      CDK_DATABASE_URL: "postgresql://conduktor:ouch-pupa-overscores-prevalent@postgresql:5432/conduktor-console"
      CDK_MONITORING_CORTEX-URL: http://conduktor-monitoring:9009/
      CDK_MONITORING_ALERT-MANAGER-URL: http://conduktor-monitoring:9010/
      CDK_MONITORING_CALLBACK-URL: http://conduktor-platform:8080/monitoring/api/
      CDK_MONITORING_NOTIFICATIONS-CALLBACK-URL: http://localhost:8080

  conduktor-monitoring:
    image: conduktor/conduktor-console-cortex:1.27.0
    environment:
      CDK_CONSOLE-URL: "http://conduktor-console:8080"


networks:
  kafka-net:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24

volumes:
  controller1-data:
    name: "controller1-data"
    driver: local
    driver_opts:
      device: ":/srv/nfs/kafka/controller1/"
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,nolock,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4
  controller2-data:
    name: "controller2-data"
    driver: local
    driver_opts:
      device: ":/srv/nfs/kafka/controller2/"
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,nolock,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4
  controller3-data:
    name: "controller3-data"
    driver: local
    driver_opts:
      device: ":/srv/nfs/kafka/controller3/"
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,nolock,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4
  broker-1-data:
    name: "broker-1-data"
    driver: local
    driver_opts:
      device: ":/srv/nfs/kafka/broker1/"
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,nolock,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4
  broker-2-data:
    name: "broker-2-data"
    driver: local
    driver_opts:
      device: ":/srv/nfs/kafka/broker2/"
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,nolock,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4
  broker-3-data:
    name: "broker-3-data"
    driver: local
    driver_opts:
      device: ":/srv/nfs/kafka/broker3/"
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,nolock,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4
  kafka-ui-data:
    driver: local
    driver_opts:
      device: :/srv/nfs/kafka-ui/
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,nolock,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4
  pg_data:
    driver: local
    driver_opts:
      device: :/srv/nfs/postgresql/
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,nolock,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4
  conduktor_data:
    driver: local
    driver_opts:
      device: :/srv/nfs/conduktor/
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,nolock,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4
