version: "3.5"
services:

  kafka-1:
    image: bisand/kafka:2.13-3.5.0
    hostname: kafka-1
    ports:
      - 19092:9092
      - 19093:9093
    deploy:
      mode: replicated
      replicas: 1
    environment:
      CLUSTER_ID: INu0PetBQfSn-5yYX6taQg
      KAFKA_LISTENERS: BROKER://kafka-1:9092,CONTROLLER://kafka-1:9093,EXTERNAL://kafka-1:19092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka-1:9092,EXTERNAL://kafka-1:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - kafka-1-data:/var/lib/kafka/data
      - cluster-id:/tmp/clusterID

  kafka-2:
    image: bisand/kafka:2.13-3.5.0
    hostname: kafka-2
    ports:
      - 29092:9092
      - 29093:9093
    deploy:
      mode: replicated
      replicas: 1
    environment:
      CLUSTER_ID: INu0PetBQfSn-5yYX6taQg
      KAFKA_LISTENERS: BROKER://kafka-2:9092,CONTROLLER://kafka-2:9093,EXTERNAL://kafka-2:29092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka-2:9092,EXTERNAL://kafka-2:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_NODE_ID: 2
      KAFKA_BROKER_ID: 2
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - kafka-2-data:/var/lib/kafka/data
      - cluster-id:/tmp/clusterID
    # command: "bash -c '/tmp/update_run.sh && /etc/confluent/docker/run'"

  kafka-3:
    image: bisand/kafka:2.13-3.5.0
    hostname: kafka-3
    ports:
      - 39092:9092
      - 39093:9093
    deploy:
      mode: replicated
      replicas: 1
    environment:
      CLUSTER_ID: INu0PetBQfSn-5yYX6taQg
      KAFKA_LISTENERS: BROKER://kafka-3:9092,CONTROLLER://kafka-3:9093,EXTERNAL://kafka-3:39092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka-3:9092,EXTERNAL://kafka-3:39092
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_NODE_ID: 3
      KAFKA_BROKER_ID: 3
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - kafka-3-data:/var/lib/kafka/data
      - cluster-id:/tmp/clusterID
    # command: "bash -c '/tmp/update_run.sh && /etc/confluent/docker/run'"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    deploy:
      mode: replicated
      replicas: 1
    environment:
      KAFKA_CLUSTERS_0_NAME: cluster-0
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
      #KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry:8085
      #KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: cluster-0
      #KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect:8083
      DYNAMIC_CONFIG_ENABLED: 'true'
      TRUST_STORE: '/opt/cert/ui-for-apache-kafka.p12'
      TRUST_STORE_PASSWORD: 'Fvck2022!'

      # OAUTH2
      AUTH_TYPE: OAUTH2
      AUTH_OAUTH2_CLIENT_GITHUB_PROVIDER: github
      AUTH_OAUTH2_CLIENT_GITHUB_CLIENTID: <client_id>
      AUTH_OAUTH2_CLIENT_GITHUB_CLIENTSECRET: <client_secret>
      AUTH_OAUTH2_CLIENT_GITHUB_SCOPE: read:org
      AUTH_OAUTH2_CLIENT_GITHUB_USER_NAME_ATTRIBUTE: login
      AUTH_OAUTH2_CLIENT_GITHUB_CUSTOM_PARAMS_TYPE: github
      AUTH_OAUTH2_CLIENT_GITHUB_REDIRECT_URI: https://kafka.publicnode.eu/login/oauth2/code/github

      # BASIC AUTH
      #AUTH_TYPE: 'LOGIN_FORM'
      #SPRING_SECURITY_USER_NAME: vr-admin
      #SPRING_SECURITY_USER_PASSWORD: Clo9s1hQcMVBPnez5mciYINXjr4y0H44
      #SPRINT_BOOT_ADMIN_CLIENT_USERNAME: vr-admin
      #SPRINT_BOOT_ADMIN_CLIENT_PASSWORD: Clo9s1hQcMVBPnez5mciYINXjr4y0H44
    configs:
      - source: kafka_ui_roles
        target: /roles.yml
      - source: kafka_ui_sprint_config
        target: /sprint-config.yml
    secrets:
      - kafka_ui_client_id
      - kafka_ui_client_secret

configs:
  kafka_ui_roles:
    external: true
  kafka_ui_sprint_config:
    external: true

secrets:
  kafka_ui_client_id:
    external: true
  kafka_ui_client_secret:
    external: true

volumes:
  cluster-id:
  kafka-1-data:
  kafka-2-data:
  kafka-3-data:
