version: "3.5"
services:

  broker:
    image: confluentinc/cp-kafka:7.6.1
    hostname: "broker{{.Task.Slot}}"
    ports:
      - 9092:9092
      - 9093:9093
      - 29092:29092
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - kafka-net
    environment:
      KAFKA_NODE_ID: '{{.Task.Slot}}'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'LISTENER_INTERNAL://broker{{.Task.Slot}}:29092,LISTENER_EXTERNAL://${PUBLIC_FQDN}:9092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker1:9093,2@broker2:9093,3@broker3:9093'
      KAFKA_LISTENERS: 'CONTROLLER://broker{{.Task.Slot}}:9093,LISTENER_INTERNAL://broker{{.Task.Slot}}:29092,LISTENER_EXTERNAL://0.0.0.0:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'LISTENER_INTERNAL'
      # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
      # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
      CLUSTER_ID: 'Asvu9rC0SdeSKJQAKgD9xw'
    volumes:
      - broker-data:/var/lib/kafka/data

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - kafka-net
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker1:29092,broker2:29092,broker3:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  connect:
    image: cnfldemos/kafka-connect-datagen:0.6.2-7.6.0
    hostname: connect
    container_name: connect
    depends_on:
      - broker
      - schema-registry
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - kafka-net
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'broker1:29092,broker2:29092,broker3:29092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR

  ksqldb-server:
    image: confluentinc/cp-ksqldb-server:7.6.1
    hostname: ksqldb-server
    container_name: ksqldb-server
    depends_on:
      - broker
      - connect
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - kafka-net
    ports:
      - "8088:8088"
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      KSQL_BOOTSTRAP_SERVERS: "broker1:29092,broker2:29092,broker3:29092"
      KSQL_HOST_NAME: ksqldb-server
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_KSQL_CONNECT_URL: "http://connect:8083"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR: 1
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: 'true'
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: 'true'

  console:
    image: docker.redpanda.com/vectorized/console:latest
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["broker1:29092","broker2:29092","broker3:29092"]
    networks:
      - kafka-net
    ports:
      - "8380:8080"
    depends_on:
      - kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8280:8080
    depends_on:
      - kafka
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - kafka-net
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      TRUST_STORE: '/opt/cert/ui-for-apache-kafka.p12'
      TRUST_STORE_PASSWORD: 'Fvck2022!'

      # OAUTH2
      # AUTH_TYPE: OAUTH2
      # AUTH_OAUTH2_CLIENT_GITHUB_PROVIDER: github
      # AUTH_OAUTH2_CLIENT_GITHUB_CLIENTID:  ${GITHUB_CLIENTID}
      # AUTH_OAUTH2_CLIENT_GITHUB_CLIENTSECRET: ${GITHUB_CLIENTSECRET}
      # AUTH_OAUTH2_CLIENT_GITHUB_SCOPE: read:org
      # AUTH_OAUTH2_CLIENT_GITHUB_USER_NAME_ATTRIBUTE: login
      # AUTH_OAUTH2_CLIENT_GITHUB_CUSTOM_PARAMS_TYPE: github
      # AUTH_OAUTH2_CLIENT_GITHUB_REDIRECT_URI: https://kafka.publicnode.eu/login/oauth2/code/github

      # BASIC AUTH
      AUTH_TYPE: 'LOGIN_FORM'
      SPRING_SECURITY_USER_NAME: ${KAFKA_UI_USERNAME}
      SPRING_SECURITY_USER_PASSWORD: ${KAFKA_UI_PASSWORD}
      SPRINT_BOOT_ADMIN_CLIENT_USERNAME: ${KAFKA_UI_USERNAME}
      SPRINT_BOOT_ADMIN_CLIENT_PASSWORD: ${KAFKA_UI_PASSWORD}
    # configs:
    #   - source: kafka_ui_roles
    #     target: /roles.yml
    #   - source: kafka_ui_sprint_config
    #     target: /sprint-config.yml
    # secrets:
    #   - kafka_ui_client_id
    #   - kafka_ui_client_secret
    volumes:
      - kafka-ui-data:/etc/kafkaui/

configs:
  kafka_ui_roles:
    external: true
  kafka_ui_sprint_config:
    external: true

secrets:
  kafka_ui_client_id:
    external: true
  kafka_ui_client_secret:
    external: true

networks:
  kafka-net:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24

volumes:
  broker-data:
    name: 'broker-data-{{.Task.Slot}}'
    driver: local
    driver_opts:
      device:	':/srv/nfs/kafka/broker{{.Task.Slot}}/'
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,nolock,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4,nfsvers=4
  kafka-ui-data:
    driver: local
    driver_opts:
      device:	:/srv/nfs/kafka-ui/
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,nolock,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4,nfsvers=4
