FROM confluentinc/cp-kafka-connect-base:7.6.1

ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components,/data/connect-jars"

RUN confluent-hub install --no-prompt snowflakeinc/snowflake-kafka-connector:2.2.2
