version: "3.5"
services:

  kafka-1:
    image: bisand/kafka:2.13-3.6.0
    hostname: "kafka-{{.Task.Slot}}"
    ports:
      - 9092:9092
      - 9093:9093
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - kafka-net
    environment:
      REPLICAS: 3
      REPLICA: "{{.Task.Slot}}"
      SERVICE: kafka-svc
      NAMESPACE: kafka-kraft
      SHARE_DIR: /mnt/kafka
      # CLUSTER_ID: ${CLUSTER_ID}
      # KAFKA_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:19092,EXTERNAL_CONTROLLER://:19093
      # KAFKA_ADVERTISED_LISTENERS: EXTERNAL://kafka.publicnode.eu:19092,INTERNAL://kafka-1:9092
      # KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER,EXTERNAL_CONTROLLER
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,EXTERNAL_CONTROLLER:PLAINTEXT
      # KAFKA_NODE_ID: 1
      # KAFKA_BROKER_ID: 1
      # KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093'
      # KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - kafka-data:/mnt/kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8180:8080
    depends_on:
      - kafka-1
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - kafka-net
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      TRUST_STORE: '/opt/cert/ui-for-apache-kafka.p12'
      TRUST_STORE_PASSWORD: 'Fvck2022!'

      # OAUTH2
      # AUTH_TYPE: OAUTH2
      # AUTH_OAUTH2_CLIENT_GITHUB_PROVIDER: github
      # AUTH_OAUTH2_CLIENT_GITHUB_CLIENTID:  ${GITHUB_CLIENTID}
      # AUTH_OAUTH2_CLIENT_GITHUB_CLIENTSECRET: ${GITHUB_CLIENTSECRET}
      # AUTH_OAUTH2_CLIENT_GITHUB_SCOPE: read:org
      # AUTH_OAUTH2_CLIENT_GITHUB_USER_NAME_ATTRIBUTE: login
      # AUTH_OAUTH2_CLIENT_GITHUB_CUSTOM_PARAMS_TYPE: github
      # AUTH_OAUTH2_CLIENT_GITHUB_REDIRECT_URI: https://kafka.publicnode.eu/login/oauth2/code/github

      # BASIC AUTH
      AUTH_TYPE: 'LOGIN_FORM'
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: disrelish-clawing-skepticism-safelight
      SPRINT_BOOT_ADMIN_CLIENT_USERNAME: admin
      SPRINT_BOOT_ADMIN_CLIENT_PASSWORD: disrelish-clawing-skepticism-safelight
    # configs:
    #   - source: kafka_ui_roles
    #     target: /roles.yml
    #   - source: kafka_ui_sprint_config
    #     target: /sprint-config.yml
    # secrets:
    #   - kafka_ui_client_id
    #   - kafka_ui_client_secret

configs:
  kafka_ui_roles:
    external: true
  kafka_ui_sprint_config:
    external: true

secrets:
  kafka_ui_client_id:
    external: true
  kafka_ui_client_secret:
    external: true

networks:
  kafka-net:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24

volumes:
  kafka-data:
    driver: local
